force-app/main/default/objects/Key_Resources_Config__mdt/Key_Resources_Config__mdt.object-meta.xml
<CustomObject>
    <description>Configuration to populate Key Resources on Article details screen in Community</description>
    <label>Key Resources Config</label>
    <pluralLabel>Key Resources Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Key_Resources_Config__mdt/fields/KA_URL__c.field-meta.xml
<CustomField>
    <fullName>KA_URL__c</fullName>
    <description>Relative URL of Knowledge Article</description>
    <inlineHelpText>Relative URL of Knowledge Article</inlineHelpText>
    <label>KA URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Key_Resources_Config__mdt/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Display Sort order for Resources within component</description>
    <inlineHelpText>Display Sort order for Resources within component</inlineHelpText>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Key_Resources_Config__mdt/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title displayed for the KA. Not using label field due to 40 char limit</description>
    <inlineHelpText>Title displayed for the KA.</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KeyResourceController.cls
public with sharing class KeyResourceController {
    
    @AuraEnabled
    public static List<TopArticle> getKeyResourceConfig(){
      
        List<TopArticle> taResponse= new List<TopArticle>();
        
        List<Key_Resources_Config__mdt>  configcmdt =[SELECT KA_URL__c, Title__c,Sort_Order__c
                                FROM Key_Resources_Config__mdt
                                ORDER BY Sort_Order__c ASC NULLS LAST];
        
        for(Key_Resources_Config__mdt config: configcmdt){
            TopArticle ta = new TopArticle();
            ta.ka_Title= config.Title__c;
            ta.ka_URL= config.KA_URL__c;
            ta.ka_sortOrder= String.valueOf(config.Sort_Order__c);
            taResponse.add(ta); 
        }
        
        return taResponse;
    }
    
    public class TopArticle{
       
        @AuraEnabled public String ka_URL;
        @AuraEnabled public String ka_Title; 
        @AuraEnabled public String ka_sortOrder; 
        
        
        public TopArticle(){
            this.ka_URL= ka_URL;
            this.ka_Title = ka_Title;
            this.ka_sortOrder = ka_sortOrder;
        }
        
    }
}